name: Automergedevelop

# Controls when the action will run. 
on:
  push:
    branches: 'feature/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    name: Develop
    runs-on: ubuntu-latest
    steps:
    - name: Mezcla develop -> feature
      uses: tukasz/direct-merge-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        source-branch: develop
        target-branch: ${{ github.ref }}
    - name: Checkout de repositorio
      uses: actions/checkout@v3.3.0
    - name: Configuración de entorno de python
      uses: actions/setup-python@v4.5.0
      with:
        python-version: '3.7'
    - name: Instalación de librerías y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt        
    - name: Correr pruebas
      id: correr-pruebas
      run: python -m unittest discover -s tests
    - name: Mezcla  feature -> develop
      if: ${{ success() }}
      uses: tukasz/direct-merge-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        source-branch: ${{ github.ref }}
        target-branch: develop
